apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add all_clusters overlay so they're applied to sandbox clusters
- ../all_clusters

# Add any additional bases (with kustomization.yaml) to be applied to sandbox clusters
#- ../../bases/project_requests/ # add manifests so projects created will be as template specifies

- ../../bases/kafka_log_fwd/ # add insecure log forwarding to kafka
- ../../bases/kafka_log_fwd/connect-kafka/ # add insecure kafka connect cluster creation

commonAnnotations:
  environment: sandbox

patchesStrategicMerge:
# Don't apply crb to give devs cluster admin, only cluster-reader will apply
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ocpdevs-cluster-admin
  $patch: delete
