apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../all_clusters/

# Add any directory (with kustomization.yaml) of manifests to be applied to sandbox clusters

#- ../../bases/misc_manifests/  # add project request template with quotas
#- ../../bases/patch_operator/patches/ # make project request template be default

commonAnnotations:
  environment: sandbox

patchesStrategicMerge:
# Don't apply crb to give devs cluster reader
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ocpdevs-cluster-reader
  $patch: delete
