apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add any directory (with kustomization.yaml) of manifests to be applied to all clusters
- ../../bases/namespace_config_operator/
- ../../bases/patch_operator/
- ../../bases/rbac/

commonAnnotations:
  environment: all-clusters
