apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add bases (with a kustomization.yaml) to be applied to all clusters
#- ../../bases/namespace_config_operator/
- ../../bases/patch_operator/
- ../../bases/rbac/
- ../../bases/logging/
- ../../bases/amq_streams/


commonAnnotations:
  environment: all-clusters
