apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add bases (with a kustomization.yaml) to be applied to all clusters
- ../../bases/namespace_config_operator/
- ../../bases/patch_operator/
- ../../bases/rbac/

# prep for logging
- ../../bases/gitops_sa/
- ../../bases/logging/

commonAnnotations:
  environment: all-clusters
