apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add any directory (with kustomization.yaml) of manifests to be applied to all clusters
- ../../cluster_apps/namespace_config_operator/
- ../../cluster_apps/patch_operator/

commonAnnotations:
  environment: all-clusters
