apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add any directory (with kustomization.yaml) of manifests to be applied to all clusters except production

commonAnnotations:
  environment: all-but-production
