kind: KafkaUser
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: logging-kafkauser
  namespace: amq-logging
  labels:
    strimzi.io/cluster: logging-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: app-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: app-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: topic
          name: infra-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: infra-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: topic
          name: audit-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: audit-topic
          patternType: literal
        operation: Describe
        host: '*'
