apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add all_clusters overlay so they're applied to management clusters
- ../all_clusters


# Add any additional bases (with kustomization.yaml) to be applied to management clusters
- ../../bases/tekton/
- ../../bases/gitops_managed_clusters/ # Add all cluster "applications" for management cluster to manage
- ../../bases/misc/ # remove default argo admin user

- ../../bases/kafka_log_fwd/tcp_log_forward/ # add secure log forwarding to kafka

commonAnnotations:
  environment: management

patchesStrategicMerge:
# Don't apply crb to give devs cluster admin, only cluster-reader will apply
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ocpdevs-cluster-admin
  $patch: delete
