apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add all cluster "applications" so management cluster can configure via gitops
- ../../bases/gitops_managed_clusters

# Add configurations for management cluster
- ../all_clusters # adds all cluster apps
- ../all_but_sandbox # removes ocpdev admin crb
- ../../bases/tekton/ # add anything that is only for management clusters

commonAnnotations:
  environment: management
