apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    strimzi.io/cluster: logging-kafka
  name: logging-kafka
  namespace: amq-logging
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - values:
                        - infra
                      key: node-role.kubernetes.io
                      operator: In
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.1'
    storage:
      type: ephemeral
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
  zookeeper:
    replicas: 3
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - values:
                        - infra
                      key: node-role.kubernetes.io
                      operator: In
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
