apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: patch-logging-producer-secret
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    patch-logging-producer-secret:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: logging-producer
        namespace: openshift-logging
      patchTemplate: >
        [
          {"op": "replace", "path": "/data/ca-bundle.crt", "value":"{{ (index (index . 1).data "ca.crt") }}"},
          {"op": "replace", "path": "/data/tls.crt", "value":"{{ (index (index . 2).data "user.crt") }}"},
          {"op": "replace", "path": "/data/tls.key", "value":"{{ (index (index . 2).data "user.key") }}"}
        ]
      patchType: application/json-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: logging-kafka-cluster-ca-cert
            #base-cluster-ca-cert # base is patched with cluster name (TODO FIX ME in kustomization overlays, this must be patched to the correct cluster name)
          namespace: amq-logging
        - apiVersion: v1
          kind: Secret
          name: logging-producer
            #cluster-logs-producer # TODO: make sure this user is correct
          namespace: amq-logging
