kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  name: logging-producer
  namespace: openshift-logging
data: # patched by patch operator
  ca-bundle.crt: ''
  tls.crt: ''
  tls.key: ''
type: Opaque
