apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add all nonprod cluster "applications"
- nonprod-rosa_cluster/nonprod-application.yaml
# Test multiple overlays to target 1 cluster
- nonprod-rosa_cluster/appcluster-nonprod.yaml
