apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add bases (with a kustomization.yaml) to be applied to application clusters
- ../../bases/tekton/

commonAnnotations:
  environment: application-clusters
