apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name:  project-request-template
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    set-project-request-template:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: Project
        name: cluster
      patchTemplate: |
        spec:
          projectRequestTemplate:
            name: project-request
      patchType: application/merge-patch+json
