apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: sbx-default-namespace
  namespace: namespace-configuration-operator
spec:
  labelSelector:
    matchLabels:
       mycom.io/project-access: developer-requested-ns
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: sbx-storage-consumption
        namespace: {{ .Name }}
      spec:
        hard:
          persistentvolumeclaims: "10"
          requests.storage: "500Gi"
