apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: infra-topic
  namespace: amq-logging
  labels:
    strimzi.io/cluster: logging-kafka
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 7200000 # 2 hour retention
    segment.bytes: 1073741824
    max.message.bytes: 10485760 # default 1048588, 1M
