apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox-cluster-config
  namespace: openshift-gitops
spec:
  destination:
    server: <cluster-api>
  project: default
  source:
    path: overlays/sandbox_clusters
    repoURL: git@github.com:cshulman/ocp_gitops_config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
