apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oob-rosa-cluster
  namespace: openshift-gitops
spec:
  destination:
    server: https://api.oob-rosa.bqnc.p1.openshiftapps.com:6443
  project: default
  source:
    path: overlays/sandbox_clusters
    repoURL: git@github.com:cshulman/ocp_gitops_config.git
    targetRevision: logging-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
