apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: app-logs
      type: kafka
      url: 'http://logging-kafka-kafka-bootstrap.amq-logging.svc.cluster.local:9092/app-topic'
    - name: infra-logs
      type: kafka
      url: 'http://logging-kafka-kafka-bootstrap.amq-logging.svc.cluster.local:9092/infra-topic'
    - name: audit-logs
      type: kafka
      url: 'http://logging-kafka-kafka-bootstrap.amq-logging.svc.cluster.local:9092/audit-topic'
  pipelines:
    - inputRefs:
        - application
      outputRefs:
        - app-logs
    - inputRefs:
        - infrastructure
      outputRefs:
        - infra-logs
    - inputRefs:
        - audit
      outputRefs:
        - audit-logs
