apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
  name: prep-logging-namespaces
  namespace: openshift-gitops
spec:
  backoffLimit: 0
  template:
    metadata:
      name: prep-logging-namespaces
    spec:
      containers:
      - name: label-openshift-logging-ns
        image: "registry.redhat.io/openshift4/ose-cli:latest"
        command: ['/bin/bash',  '-c', "oc label namespace openshift-logging openshift.io/cluster-monitoring=true"]
      - name: label-openshift-operators-redhat-ns
        image: "registry.redhat.io/openshift4/ose-cli:latest"
        command: ['/bin/bash',  '-c', 'oc label namespace openshift-operators-redhat openshift.io/cluster-monitoring=true']
      - name: annotate-openshift-operators-redhat-ns
        image: "registry.redhat.io/openshift4/ose-cli:latest"
        command: ['/bin/bash',  '-c', 'oc annotate namespace openshift-operators-redhat openshift.io/node-selector=""']
      restartPolicy: OnFailure
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "gitops-superuser"
