apiVersion: v1
kind: Secret
metadata:
  name: <cluster-name>-config-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: <cluster-name>
  server: <cluster-url>
  config: |
    {
      "bearerToken": "<bearer-token>",
      "tlsClientConfig": {
        "serverName": "kubernetes.default.svc",
        "insecure": true
      }
    }

