apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- sandbox/ # add all defined sandbox clusters
- nonproduction/ # add all defined nonproduction clusters
- production/ # add all defined production clusters

commonLabels:
  cluster-apps: mgmt-managed
