apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Add all cluster "applictions"
- sbx/ # add all defined sandbox clusters
- nonprod/ # add all defined nonprod clusters
- prod/ # add all defined production clusters
