apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../all_clusters # adds all cluster apps

# Add any directory (with kustomization.yaml) of manifests to be applied to production clusters

commonAnnotations:
  environment: production

patchesStrategicMerge:
# Don't apply crb to give devs cluster admin, only cluster-reader will apply
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ocpdevs-cluster-admin
  $patch: delete
