apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add all_clusters overlay so they're applied to production clusters
- ../all_clusters

# Add any additional bases (with kustomization.yaml) to be applied to production clusters

- ../../bases/kafka_log_fwd/tcp_log_forward/ # add secure log forwarding to kafka

commonAnnotations:
  environment: production

patchesStrategicMerge:
# Don't apply crb to give devs cluster admin, only cluster-reader will apply
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ocpdevs-cluster-admin
  $patch: delete
