apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sbx-rosa-config
  namespace: openshift-gitops
spec:
  destination:
    server: https://api.sbx-rosa.rt0q.p1.openshiftapps.com:6443
  project: default
  source:
    path: overlays/sandbox_clusters
    repoURL: git@github.com:cshulman/ocp_gitops_config.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=false
