apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nonprod-rosa-config
  namespace: openshift-gitops
spec:
  destination:
    server: https://api.nonprod-rosa.bqnc.p1.openshiftapps.com:6443
  project: default
  source:
    path: overlays/nonprod_clusters
    repoURL: git@github.com:cshulman/ocp_gitops_config.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=false
