apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- log-forwarder.yaml
- remove-kafka-auth-patch.yaml
- kafka/

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous # prevent argo re-syncing loop
